/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.enrollment.model;

import java.util.Objects;

import org.threeten.bp.OffsetDateTime;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * CreditorAccountsDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-20T15:46:11.567Z")
public class CreditorAccountsDto {
  @SerializedName("destinationDNI")
  private String destinationDNI = null;

  @SerializedName("identification")
  private String identification = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("secondaryIdentification")
  private String secondaryIdentification = null;

  @SerializedName("validThru")
  private OffsetDateTime validThru = null;

  public CreditorAccountsDto destinationDNI(String destinationDNI) {
    this.destinationDNI = destinationDNI;
    return this;
  }

   /**
   * Get destinationDNI
   * @return destinationDNI
  **/
  @ApiModelProperty(value = "")
  public String getDestinationDNI() {
    return destinationDNI;
  }

  public void setDestinationDNI(String destinationDNI) {
    this.destinationDNI = destinationDNI;
  }

  public CreditorAccountsDto identification(String identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Get identification
   * @return identification
  **/
  @ApiModelProperty(value = "")
  public String getIdentification() {
    return identification;
  }

  public void setIdentification(String identification) {
    this.identification = identification;
  }

  public CreditorAccountsDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreditorAccountsDto secondaryIdentification(String secondaryIdentification) {
    this.secondaryIdentification = secondaryIdentification;
    return this;
  }

   /**
   * Get secondaryIdentification
   * @return secondaryIdentification
  **/
  @ApiModelProperty(value = "")
  public String getSecondaryIdentification() {
    return secondaryIdentification;
  }

  public void setSecondaryIdentification(String secondaryIdentification) {
    this.secondaryIdentification = secondaryIdentification;
  }

  public CreditorAccountsDto validThru(OffsetDateTime validThru) {
    this.validThru = validThru;
    return this;
  }

   /**
   * Get validThru
   * @return validThru
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getValidThru() {
    return validThru;
  }

  public void setValidThru(OffsetDateTime validThru) {
    this.validThru = validThru;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditorAccountsDto creditorAccountsDto = (CreditorAccountsDto) o;
    return Objects.equals(this.destinationDNI, creditorAccountsDto.destinationDNI) &&
        Objects.equals(this.identification, creditorAccountsDto.identification) &&
        Objects.equals(this.name, creditorAccountsDto.name) &&
        Objects.equals(this.secondaryIdentification, creditorAccountsDto.secondaryIdentification) &&
        Objects.equals(this.validThru, creditorAccountsDto.validThru);
  }

  @Override
  public int hashCode() {
    return Objects.hash(destinationDNI, identification, name, secondaryIdentification, validThru);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditorAccountsDto {\n");
    
    sb.append("    destinationDNI: ").append(toIndentedString(destinationDNI)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    secondaryIdentification: ").append(toIndentedString(secondaryIdentification)).append("\n");
    sb.append("    validThru: ").append(toIndentedString(validThru)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

