/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.enrollment.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * DebtorAccountsDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-20T15:46:11.567Z")
public class DebtorAccountsDto {
  @SerializedName("creditorAccounts")
  private List<CreditorAccountsDto> creditorAccounts = null;

  @SerializedName("destinationDNI")
  private String destinationDNI = null;

  @SerializedName("identification")
  private String identification = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("secondaryIdentification")
  private String secondaryIdentification = null;

  public DebtorAccountsDto creditorAccounts(List<CreditorAccountsDto> creditorAccounts) {
    this.creditorAccounts = creditorAccounts;
    return this;
  }

  public DebtorAccountsDto addCreditorAccountsItem(CreditorAccountsDto creditorAccountsItem) {
    if (this.creditorAccounts == null) {
      this.creditorAccounts = new ArrayList<CreditorAccountsDto>();
    }
    this.creditorAccounts.add(creditorAccountsItem);
    return this;
  }

   /**
   * Get creditorAccounts
   * @return creditorAccounts
  **/
  @ApiModelProperty(value = "")
  public List<CreditorAccountsDto> getCreditorAccounts() {
    return creditorAccounts;
  }

  public void setCreditorAccounts(List<CreditorAccountsDto> creditorAccounts) {
    this.creditorAccounts = creditorAccounts;
  }

  public DebtorAccountsDto destinationDNI(String destinationDNI) {
    this.destinationDNI = destinationDNI;
    return this;
  }

   /**
   * Get destinationDNI
   * @return destinationDNI
  **/
  @ApiModelProperty(value = "")
  public String getDestinationDNI() {
    return destinationDNI;
  }

  public void setDestinationDNI(String destinationDNI) {
    this.destinationDNI = destinationDNI;
  }

  public DebtorAccountsDto identification(String identification) {
    this.identification = identification;
    return this;
  }

   /**
   * Get identification
   * @return identification
  **/
  @ApiModelProperty(value = "")
  public String getIdentification() {
    return identification;
  }

  public void setIdentification(String identification) {
    this.identification = identification;
  }

  public DebtorAccountsDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DebtorAccountsDto secondaryIdentification(String secondaryIdentification) {
    this.secondaryIdentification = secondaryIdentification;
    return this;
  }

   /**
   * Get secondaryIdentification
   * @return secondaryIdentification
  **/
  @ApiModelProperty(value = "")
  public String getSecondaryIdentification() {
    return secondaryIdentification;
  }

  public void setSecondaryIdentification(String secondaryIdentification) {
    this.secondaryIdentification = secondaryIdentification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DebtorAccountsDto debtorAccountsDto = (DebtorAccountsDto) o;
    return Objects.equals(this.creditorAccounts, debtorAccountsDto.creditorAccounts) &&
        Objects.equals(this.destinationDNI, debtorAccountsDto.destinationDNI) &&
        Objects.equals(this.identification, debtorAccountsDto.identification) &&
        Objects.equals(this.name, debtorAccountsDto.name) &&
        Objects.equals(this.secondaryIdentification, debtorAccountsDto.secondaryIdentification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditorAccounts, destinationDNI, identification, name, secondaryIdentification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DebtorAccountsDto {\n");
    
    sb.append("    creditorAccounts: ").append(toIndentedString(creditorAccounts)).append("\n");
    sb.append("    destinationDNI: ").append(toIndentedString(destinationDNI)).append("\n");
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    secondaryIdentification: ").append(toIndentedString(secondaryIdentification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

