/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.enrollment.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * EnrollmentAccountsDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-03-20T15:46:11.567Z")
public class EnrollmentAccountsDto {
  @SerializedName("clientId")
  private String clientId = null;

  @SerializedName("debtorAccount")
  private DebtorAccountsDto debtorAccount = null;

  @SerializedName("enrollmentId")
  private String enrollmentId = null;

  public EnrollmentAccountsDto clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  @ApiModelProperty(value = "")
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public EnrollmentAccountsDto debtorAccount(DebtorAccountsDto debtorAccount) {
    this.debtorAccount = debtorAccount;
    return this;
  }

   /**
   * Get debtorAccount
   * @return debtorAccount
  **/
  @ApiModelProperty(value = "")
  public DebtorAccountsDto getDebtorAccount() {
    return debtorAccount;
  }

  public void setDebtorAccount(DebtorAccountsDto debtorAccount) {
    this.debtorAccount = debtorAccount;
  }

  public EnrollmentAccountsDto enrollmentId(String enrollmentId) {
    this.enrollmentId = enrollmentId;
    return this;
  }

   /**
   * Get enrollmentId
   * @return enrollmentId
  **/
  @ApiModelProperty(value = "")
  public String getEnrollmentId() {
    return enrollmentId;
  }

  public void setEnrollmentId(String enrollmentId) {
    this.enrollmentId = enrollmentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnrollmentAccountsDto enrollmentAccountsDto = (EnrollmentAccountsDto) o;
    return Objects.equals(this.clientId, enrollmentAccountsDto.clientId) &&
        Objects.equals(this.debtorAccount, enrollmentAccountsDto.debtorAccount) &&
        Objects.equals(this.enrollmentId, enrollmentAccountsDto.enrollmentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientId, debtorAccount, enrollmentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnrollmentAccountsDto {\n");
    
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    debtorAccount: ").append(toIndentedString(debtorAccount)).append("\n");
    sb.append("    enrollmentId: ").append(toIndentedString(enrollmentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

